# Generated by Django 3.2 on 2022-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active_expired',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=200),
        ),
    ]
