# Generated by Django 3.2 on 2022-03-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_booth_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
    ]
