# Generated by Django 3.2 on 2022-03-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_image_url'),
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
    ]
