# Generated by Django 3.2 on 2022-03-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_image_url'),
        ('events', '0008_auto_20220313_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
    ]
