# Generated by Django 3.2 on 2022-03-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='image',
        ),
    ]
