# Generated by Django 3.2 on 2022-02-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='event_date',
        ),
    ]
