# Generated by Django 3.2 on 2022-02-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuimages',
            options={'verbose_name_plural': 'Menu Images'},
        ),
    ]
