# Generated by Django 3.2 on 2022-03-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image_url',
        ),
    ]
